// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoDeGradoFundacion.Data;

#nullable disable

namespace ProyectoDeGradoFundacion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418215320_UpdateCitas")]
    partial class UpdateCitas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cita_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CitaId"));

                    b.Property<string>("CitaExternaId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cita_externa_id");

                    b.Property<string>("EstadoCita")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado_cita");

                    b.Property<DateTime?>("FechaAnalisis")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_analisis");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creado");

                    b.Property<string>("GradoRetinopatia")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("grado_retinopatia");

                    b.Property<string>("ImagenOjoDerecho")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagen_ojo_derecho");

                    b.Property<string>("ImagenOjoIzquierdo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagen_ojo_izquierdo");

                    b.Property<string>("ObservacionesOjoDerecho")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("observaciones_ojo_derecho");

                    b.Property<string>("ObservacionesOjoIzquierdo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("observaciones_ojo_izquierdo");

                    b.Property<string>("PacienteExternoId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("paciente_externo_id");

                    b.Property<string>("ReportePdf")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reporte_pdf");

                    b.Property<string>("ResultadoOjoDerecho")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("resultado_ojo_derecho");

                    b.Property<string>("ResultadoOjoIzquierdo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("resultado_ojo_izquierdo");

                    b.Property<string>("TipoRetinopatia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_retinopatia");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("CitaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.EncuestaUsuario", b =>
                {
                    b.Property<int>("EncuestaUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("encuesta_usuario_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EncuestaUsuarioId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("EncuestaUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("encuesta_usuario");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.EncuestaUsuarioDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("EncuestaUsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("encuesta_usuario_id");

                    b.Property<int?>("OpcionId")
                        .HasColumnType("int")
                        .HasColumnName("opcion_id");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int")
                        .HasColumnName("pregunta_id");

                    b.Property<string>("TextoRespuesta")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("texto_respuesta");

                    b.HasKey("DetalleId");

                    b.HasIndex("EncuestaUsuarioId");

                    b.HasIndex("OpcionId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("encuesta_usuario_detalle");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Opcion", b =>
                {
                    b.Property<int>("OpcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("opcion_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OpcionId"));

                    b.Property<string>("NombreOpcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_opcion");

                    b.HasKey("OpcionId");

                    b.ToTable("opciones");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.OpcionRespuesta", b =>
                {
                    b.Property<int>("OpcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("opcion_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OpcionId"));

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int")
                        .HasColumnName("pregunta_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("texto");

                    b.Property<bool?>("ValorLogico")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("valor_logico");

                    b.HasKey("OpcionId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("opcion_respuesta");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("PermisoId");

                    b.ToTable("permisos");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Pregunta", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pregunta_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PreguntaId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activa");

                    b.Property<string>("CondicionGenero")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("condicion_genero");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("texto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("PreguntaId");

                    b.ToTable("preguntas");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.RolPermisoOpcion", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    b.Property<int>("OpcionId")
                        .HasColumnType("int")
                        .HasColumnName("opcion_id");

                    b.HasKey("RolId", "PermisoId", "OpcionId");

                    b.HasIndex("OpcionId");

                    b.HasIndex("PermisoId");

                    b.ToTable("roles_permisos_opciones");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ApellidoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido_usuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<int>("EstadoUsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("estado_usuario_id");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creado");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tipo_identificacion");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Cita", b =>
                {
                    b.HasOne("ProyectoDeGradoFundacion.Models.Usuario", "Usuario")
                        .WithMany("Citas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.EncuestaUsuario", b =>
                {
                    b.HasOne("ProyectoDeGradoFundacion.Models.Usuario", "Usuario")
                        .WithMany("EncuestasUsuario")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.EncuestaUsuarioDetalle", b =>
                {
                    b.HasOne("ProyectoDeGradoFundacion.Models.EncuestaUsuario", "EncuestaUsuario")
                        .WithMany("Detalles")
                        .HasForeignKey("EncuestaUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoDeGradoFundacion.Models.OpcionRespuesta", "OpcionRespuesta")
                        .WithMany("EncuestaUsuarioDetalles")
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoDeGradoFundacion.Models.Pregunta", "Pregunta")
                        .WithMany("EncuestaUsuarioDetalles")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncuestaUsuario");

                    b.Navigation("OpcionRespuesta");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.OpcionRespuesta", b =>
                {
                    b.HasOne("ProyectoDeGradoFundacion.Models.Pregunta", "Pregunta")
                        .WithMany("OpcionesRespuesta")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.RolPermisoOpcion", b =>
                {
                    b.HasOne("ProyectoDeGradoFundacion.Models.Opcion", "Opcion")
                        .WithMany("RolesPermisosOpciones")
                        .HasForeignKey("OpcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoDeGradoFundacion.Models.Permiso", "Permiso")
                        .WithMany("RolesPermisosOpciones")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoDeGradoFundacion.Models.Rol", "Rol")
                        .WithMany("RolesPermisosOpciones")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opcion");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoDeGradoFundacion.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.EncuestaUsuario", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Opcion", b =>
                {
                    b.Navigation("RolesPermisosOpciones");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.OpcionRespuesta", b =>
                {
                    b.Navigation("EncuestaUsuarioDetalles");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Permiso", b =>
                {
                    b.Navigation("RolesPermisosOpciones");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Pregunta", b =>
                {
                    b.Navigation("EncuestaUsuarioDetalles");

                    b.Navigation("OpcionesRespuesta");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Rol", b =>
                {
                    b.Navigation("RolesPermisosOpciones");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoDeGradoFundacion.Models.Usuario", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("EncuestasUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
